groups:
  - id: gcp.project
    prefix: gcp.project
    type: resource
    stability: experimental
    brief: >
      Project related attributes.
    attributes:
      - ref: gcp.project.id
        requirement_level: recommended


